volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: julia949/foodgram-backend:latest
    env_file:
      - .env
    volumes:
      - static:/static/
      - media:/app/media
      - ./data:/app/data
    depends_on:
      - db

  frontend:
    image: julia949/foodgram-frontend:latest
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  nginx:
    image: julia949/foodgram-nginx:latest
    env_file: .env
    depends_on:
      - backend
      - frontend
    ports:
      - "8080:80"
    volumes:
      - static:/static/
      - media:/app/media

