

services:

  db:
    image: postgres:15-alpine
    container_name: db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: julia949/foodgram-backend:latest
    container_name: backend
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - static_data:/app/static
      - media_data:/app/media
    depends_on:
      - db

  frontend:
    image: julia949/foodgram-frontend:latest
    container_name: frontend
    restart: "no"
    volumes:
      - frontend_build:/app/build

  nginx:
    image: nginx:1.25.4-alpine
    container_name: foodgram-proxy
    restart: unless-stopped
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - frontend_build:/usr/share/nginx/html:ro
      - ./docs:/usr/share/nginx/html/api/docs:ro
      - static_data:/var/html/static:ro
      - media_data:/var/html/media:ro

volumes:
  postgres_data:
  static_data:
  media_data:
  frontend_build:
