# Generated by Django 4.2.20 on 2025-07-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='measure',
            new_name='amount',
        ),
    ]
